version: "3.8"

services:
  prod:
    build:
      context: .
      target: prod
    ports:
      - "3000:3000"
  dev:
    build:
      context: .
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
